"""Launch defaults kept importable for tests and operator documentation."""


LAUNCH_DEFAULTS = {
    "use_lidar": "true",
    "use_camera": "false",
    "use_mapping": "false",
    "use_rviz": "false",
    "use_sim_time": "false",
    "support_min_points_per_cell": "3",
    "use_inflation": "false",
    "inflation_radius": "0.55",
    "cost_scaling_factor": "3.0",
    "publish_camera_tf": "false",
    "use_robot_model": "true",
    "publish_lidar_tf": "true",
    "lidar_x": "0.330",
    "lidar_y": "-0.265",
    "lidar_z": "0.320",
    "lidar_yaw": "0.392699082",
    "lidar_pitch": "0.0",
    "lidar_roll": "0.0",
    "publish_left_lidar_tf": "true",
    "lidar_left_x": "0.330",
    "lidar_left_y": "0.265",
    "lidar_left_z": "0.320",
    "lidar_left_yaw": "-0.392699082",
    "lidar_left_pitch": "0.0",
    "lidar_left_roll": "0.0",
    "base_camera_x": "-0.360",
    "base_camera_y": "0.265",
    "base_camera_z": "1.300",
    "base_camera_yaw": "0.0",
    "base_camera_pitch": "0.0",
    "base_camera_roll": "0.0",
}


SENSOR_TRANSFORMS = {
    "lidar_right_link": {
        "x": LAUNCH_DEFAULTS["lidar_x"],
        "y": LAUNCH_DEFAULTS["lidar_y"],
        "z": LAUNCH_DEFAULTS["lidar_z"],
        "yaw": LAUNCH_DEFAULTS["lidar_yaw"],
        "pitch": LAUNCH_DEFAULTS["lidar_pitch"],
        "roll": LAUNCH_DEFAULTS["lidar_roll"],
        "parent": "base_link",
        "child": "lidar_right_link",
    },
    "lidar_left_link": {
        "x": LAUNCH_DEFAULTS["lidar_left_x"],
        "y": LAUNCH_DEFAULTS["lidar_left_y"],
        "z": LAUNCH_DEFAULTS["lidar_left_z"],
        "yaw": LAUNCH_DEFAULTS["lidar_left_yaw"],
        "pitch": LAUNCH_DEFAULTS["lidar_left_pitch"],
        "roll": LAUNCH_DEFAULTS["lidar_left_roll"],
        "parent": "base_link",
        "child": "lidar_left_link",
    },
    "camera_link": {
        "x": LAUNCH_DEFAULTS["base_camera_x"],
        "y": LAUNCH_DEFAULTS["base_camera_y"],
        "z": LAUNCH_DEFAULTS["base_camera_z"],
        "yaw": LAUNCH_DEFAULTS["base_camera_yaw"],
        "pitch": LAUNCH_DEFAULTS["base_camera_pitch"],
        "roll": LAUNCH_DEFAULTS["base_camera_roll"],
        "parent": "base_link",
        "child": "camera_link",
    },
}
